# Generated by Django 5.1.5 on 2025-02-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('return_type', models.TextField()),
                ('arguments', models.JSONField()),
                ('file', models.TextField()),
                ('line', models.IntegerField()),
                ('static', models.BooleanField(default=False)),
                ('const', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='FunctionRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('call_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from', to='FunctionServey.function')),
                ('call_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to', to='FunctionServey.function')),
            ],
            options={
                'db_table': 'function_relation',
            },
        ),
    ]
