# Generated by Django 5.1.5 on 2025-02-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionSurvey', '0002_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='function',
            name='return_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
