# Generated by Django 5.1.5 on 2025-03-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionSurvey', '0003_alter_function_name_alter_function_return_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('file', models.TextField()),
                ('line', models.IntegerField()),
                ('static', models.BooleanField(default=False)),
                ('const', models.BooleanField(default=False)),
                ('is_pointer', models.BooleanField(default=True)),
                ('is_prototype', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_project', to='FunctionSurvey.project')),
                ('scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_function', to='FunctionSurvey.function')),
            ],
            options={
                'db_table': 'variable',
            },
        ),
    ]
