# Generated by Django 5.1.5 on 2025-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionSurvey', '0004_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='end_line',
            field=models.IntegerField(null=True),
        ),
    ]
